data:
  train_path: data/X_text.csv
  target_path: data/Y_tags.csv
  test_path: data/test/X_text_test.csv
  test_target_path: data/test/Y_tags_test.csv

lda:
  num_topics: 10
  passes: 10
  random_state: 42
  model_path: models/lda/lda_model.gensim

vectorizer:
  method: tfidf  # or count
  params:
    max_features: 3000
    stop_words: english

mlflow:
  experiment_name: logreg_modeling

task_type: supervised # or lda

supervised:
  model: logreg  # choice: logreg, random_forest, xgboost
  models:

    logreg:
      base_params:
        solver: saga
        max_iter: 1000
        random_state: 42
        n_jobs: -1

    random_forest:
      base_params:
        random_state: 42
        n_jobs: -1
      search_params:
        estimator__n_estimators: [100, 200]
        estimator__max_depth: [10, 20, 50]
        estimator__min_samples_leaf: [1, 5, 10]

    xgboost:
      base_params:
        eval_metric: logloss
        use_label_encoder: False
        random_state: 42
        n_jobs: -1
      search_params:
        estimator__n_estimators: [100, 300]
        estimator__max_depth: [3, 6, 10]
        estimator__learning_rate: [0.01, 0.1, 0.2]

classifier:
  model_name: logreg
  multilabel_targets_path: data/Y_tags.csv
  model_path: models/supervised/classifier_logreg.pkl