data:
  train_path: data/X_text.csv
  target_path: data/Y_tags.csv
  test_path: data/test/X_text_test.csv
  test_target_path: data/test/Y_tags_test.csv
  use_sample: false # true for sample data or false for full data
  sample:
    size: 5000
    top_n_tags: 20
    output_dir: data/sampled
    seed: 42

lda:
  num_topics: 10
  passes: 10
  random_state: 42
  model_path: models/lda/lda_model.gensim

vectorizer:
  method: tfidf
  params:
    max_features: 2000
    stop_words: english

mlflow:
  experiment_name: xgboost full data # enter experiment_name
  tracking_uri: sqlite:///mlflow.db
  registry_uri: sqlite:///mlflow.db
  artifacts_location: ./mlruns

task_type: supervised # supervised or lda

supervised:
  model: xgboost # choices: logreg, random_forest, xgboost
  models:
    logreg:
      base_params:
        solver: saga
        max_iter: 1000
        random_state: 42
        n_jobs: -1
        class_weight: "balanced"
        penalty: "l2"
        C: 1.0
      search_params:
        estimator__C: [0.1, 1.0]
        estimator__class_weight: ["balanced"]
        estimator__penalty: ["l2"]
        estimator__max_iter: [1000]

    random_forest:
      base_params:
        random_state: 42
        n_jobs: -1
        n_estimators: 200
        max_depth: 20
        min_samples_split: 5
        min_samples_leaf: 2
        max_features: "sqrt"
        class_weight: "balanced"
      search_params:
        estimator__n_estimators: [100, 200, 300]
        estimator__max_depth: [10, 20, 30]
        estimator__min_samples_split: [2, 5]
        estimator__min_samples_leaf: [1, 2]
        estimator__max_features: ["sqrt", "log2"]

    xgboost:
      base_params:
        eval_metric: logloss
        use_label_encoder: False
        random_state: 42
        n_jobs: -1
        n_estimators: 200
        max_depth: 6
        learning_rate: 0.1
        subsample: 0.8
        colsample_bytree: 0.8
      search_params:
        estimator__n_estimators: [100, 200, 300]
        estimator__max_depth: [4, 6, 8]
        estimator__learning_rate: [0.05, 0.1, 0.2]
        estimator__subsample: [0.8, 1.0]
        estimator__colsample_bytree: [0.8, 1.0]

classifier:
  model_name: logreg
  multilabel_targets_path: data/Y_tags.csv
  model_path: models/supervised/classifier_logreg.pkl
